### ISSUE TITLE
custom actions for channels/realtime updates

### ISSUE THREAD

**Issue by fratzinger** [fratzinger/feathers-casl#10]
Currently channels get filtered by action `get`. 
This should be a option. Similar to `multi`-actions, that can be used by option, there could be use-cases for actions like:
- `receive`: get all realtime updates
- `receive:created`: get only `created` events
- `receive:updated`: get only `updates` events
- `receive:patched`: get only `patched` events
- `receive:removed`: get only `removed` events

Even with `fields` and `conditions` this could become powerful.

**Comment by J3m5** [comment]
This would be a nice addition.
I've been thinking about another feature related to events but not directly related to casl, but still.

We could create one channel per service at startup, and then register clients only when they call a service for the first time and if they have the permissions.
Because apart for a notification system, I don't see any reason to receive events for resources you didn't requested yet.
This could be optional of course, (opt-in or opt-out).

This would reduce the load on the server by reducing the checks for the permissions and the sending of the events.
It would also reduce the amount of data stored on the client if a store is used.

The only downside is that, for each request, it would check if the client is already in the channel ( done automatically in the channels when you add a connection if I remember correctly)

**Comment by fratzinger** [comment]
@J3m5: Indeed this is nothing, casl could really help. I moved this to `Feathers-Vuex`. Maybe it's the wrong place too, but lets see. We'll keep this issue for casl-related things :)
