### ISSUE TITLE
Next version for feathers 5

### ISSUE THREAD

**Issue by anbraten** [fratzinger/feathers-casl#48]
We are currently trying to use your plugin with feathers version 5.  To get it to work some dependencies like the `feathers-utils` & `feathers-hooks-common` libs have to be updated as well. I saw that you already planned that somehow for `feathers-utils`: https://github.com/fratzinger/feathers-utils/issues/4. As it seems that for example "only" `getItems` & `replaceItems` is used from `feathers-hooks-common` do you think it would be possible to add a light version / just the needed code of that functionality to `feathers-casl` directly, so dependencies would be reduced? 
Would like to do / help you with that update.

**Comment by fratzinger** [comment]
Thanks for the investigation!
I like to use `feathers-hooks-common` because I don't want to reinvent the wheel for simple functions like `getItems` & `replaceItems`. But if that stops from moving to feathers@5, thats surely a bummer.

I haven't migrated to feathers@5 myself, but I would love to add support. What are the reasons why it's not working? `feathers-utils` is used quite deeply with `mergeQuery`. I would like to keep that as is but am open to migrating to feathers@5.

Greets from Rostock!

**Comment by yobdl** [comment]
I tried `feathers-casl ^0.7.1` with Dove but got the following error at compilation :

<img width="905" alt="Capture d’écran 2022-01-21 à 22 49 31" src="https://user-images.githubusercontent.com/98084926/150604868-54b3acba-2933-4167-b566-ae3b60f63d93.png">

Any advice on how to achieve compability with Dove would be much appreciated.

**Comment by fratzinger** [comment]
Hey guys, we have a pre-release for dove now.

I continued my work in the dove branch: https://github.com/fratzinger/feathers-casl/tree/dove
And finally released a pre version as `feathers-casl@pre` (`npm install feathers-casl@pre`). It got a few new things:
- feathers dove support for `@feathersjs/memory`, `@feathersjs/knex`, `@feathersjs/mongodb`, `feathers-sequelize@pre`
- ‼️ no support for `feathers-memory`, `feathers-knex`, `feathers-objection`, `feathers-mongodb`, `feathers-mongoose` because they aren't compatible with dove (yet) (or at least I don't know of a support)
- cjs & esm support by https://github.com/unjs/unbuild
- peerDependency `@casl/ability`: To follow best practices `feathers-casl` no longer exports stuff from `@casl/ability`, so you have to install it on your own and define the `ability` with it. A few tests are failing with the newest major release of `@casl/ability` (v6), so currently only `@casl/ability@5` is supported. But `@casl/ability@5` was used in `feathers-casl` before. I'll work on that in a future pre release.
- around hook: the hook `authorize` can also be used as an `around` hook now. I've added tests for `@feathersjs/memory` to make sure it works correctly.
- tests with vitest
- many more small things have changed

Things I have to do in future pre releases:
- support for `@casl/ability@6`
- add `around` hook for `checkBasicPermission`
- update the docs. A few things have to be updated. Especially the supported adapters. I haven't touched the docs yet.
- maybe add support for `feathers-objection`, `feathers-mongoose` if they got support for dove
- maybe add support for custom methods somehow

I close this for now. Feel free to open new issues when you tested out the new pre release.
