### ISSUE TITLE
Support for casl v6 ?

### ISSUE THREAD

**Issue by mdartic** [fratzinger/feathers-casl#83]
Hi,

I'm trying the latest version 1.0.0-1, and I discover the `peerDependencies` of `casl` is limited to `>= 5.0.0 < 6`.

Do you think we could upgrade `feathers-casl` to use the latest version of casl ? (6, actually)

I don't know which breaking changes occur between 5 and 6.

Do you think there could be some breaking changes ?

**Comment by fratzinger** [comment]
Some tests fail definitely for `casl@6`. I had no time to investigate yet. I don't know what the problem is yet. But yes, I would love to update to `casl@6`. Any help with that would be highly appreciated.

FYI: Please remind, that the docs aren't up to date for `feathers-casl@1.0.0-1` yet. There are some other quirks than the `peerDependencies`. Follow this thread for more info: https://discord.com/channels/509848480760725514/1046538218855727194

**Comment by fratzinger** [comment]
support is there with version `feathers-casl` v1. Thanks for the ticket.
